# -*- coding: utf-8 -*-
"""Profit Margin Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IpC5gRiSV8fdVtrP3LTtF6SBNwrMwCV
"""

import streamlit as st
import pandas as pd
import io

# --- CONFIGURATION & STYLING ---
st.set_page_config(page_title="2026 Marketplace Master", layout="wide", page_icon="📈")

def calculate_2026_economics(platform, price, cogs, region="National"):
    """
    March 2026 Verified Rules:
    - Amazon: 0% referral for items <= ₹300 (135+ categories).
    - Flipkart: 0% commission for items <= ₹1000 (Marketplace-wide).
    - Income Tax: 0.1% TDS (Section 194-O) from Oct 2024 onwards.
    - GST TCS: 0.5% (Reduced from 1% in late 2025).
    """
    gst_rate = 0.18

    if platform == "Amazon":
        referral = 0 if price <= 300 else (price * 0.12)
        closing = 5 if price <= 250 else 30 if price <= 1000 else 60
        shipping = 45 if region == "Local" else 75
        total_fees = referral + closing + shipping
        # Return Policy: Referral refunded, Shipping/Closing lost + 2% processing
        return_loss = closing + shipping + (price * 0.02)

    elif platform == "Flipkart":
        commission = 0 if price <= 1000 else (price * 0.08)
        fixed = 15 if price <= 500 else 35
        shipping = 40 if region == "Local" else 65
        total_fees = commission + fixed + shipping
        # Return Policy: Reverse shipping (1.2x) + Fixed fee
        return_loss = (shipping * 1.2) + fixed

    else: # Swiggy Instamart / Quick Commerce
        total_fees = (price * 0.22) + 12
        return_loss = total_fees * 0.6

    # Tax Recovery Math (March 2026 Standards)
    fee_gst = total_fees * gst_rate
    tcs_gst = price * 0.005    # 0.5% GST TCS
    tds_it = price * 0.001     # 0.1% Income Tax TDS

    net_payout = price - (total_fees + fee_gst + tcs_gst + tds_it)
    unit_profit = net_payout - cogs
    margin_pct = (unit_profit / price) * 100 if price > 0 else 0

    # Recovery Ratio: How many good sales cover 1 bad return?
    total_loss_per_return = return_loss + (return_loss * gst_rate) + 25 # +Pkg/Labour
    recovery_ratio = total_loss_per_return / unit_profit if unit_profit > 0 else 999

    return {
        "payout": round(net_payout, 2),
        "profit": round(unit_profit, 2),
        "margin": round(margin_pct, 2),
        "return_loss": round(total_loss_per_return, 2),
        "recovery_ratio": round(recovery_ratio, 1),
        "itc": round(fee_gst, 2),
        "tcs": round(tcs_gst, 2),
        "tds": round(tds_it, 2)
    }

# --- UI HEADER ---
st.title("💰 2026 Marketplace Command Center")
st.caption("Updated: March 2026 | TDS: 0.1% | TCS: 0.5% | Zero-Fee Tiers Active")

# --- APP TABS ---
tab1, tab2, tab3 = st.tabs(["🚀 Single SKU Profit", "📊 Bulk & Sample CSV", "🛡️ Buy Box & Ladder"])

with tab1:
    col1, col2, col3 = st.columns([1, 1.2, 1.2])
    with col1:
        st.subheader("Input Data")
        plat = st.selectbox("Marketplace", ["Amazon", "Flipkart", "Swiggy Instamart"])
        price = st.number_input("Selling Price (₹)", value=1200.0, step=10.0)
        cogs = st.number_input("Landing Cost (₹)", value=550.0)
        region = st.radio("Region", ["Local", "National"])
        data = calculate_2026_economics(plat, price, cogs, region)

    with col2:
        st.subheader("Payout & Profit")
        st.metric("Net Bank Payout", f"₹{data['payout']}")
        st.metric("Net Profit / Unit", f"₹{data['profit']}", delta=f"{data['margin']}% Margin")

        st.divider()
        st.write("**Marketing Ads Simulator**")
        target_acos = st.slider("Target ACOS %", 0.0, float(max(0.1, data['margin'])), float(data['margin']*0.7))
        ad_spend = price * (target_acos / 100)
        st.info(f"Profit after Ads: **₹{data['profit'] - ad_spend:.2f}**")

    with col3:
        st.subheader("Returns & Tax")
        st.error(f"Loss/Return: ₹{data['return_loss']}")
        st.warning(f"Recovery Ratio: {data['recovery_ratio']} units")
        st.caption("Sales needed to recover ONE return loss.")

        st.divider()
        st.subheader("📑 Tax Claims")
        st.info(f"Total ITC/Cash Ledger: ₹{data['itc'] + data['tcs'] + data['tds']}")

with tab2:
    st.subheader("Bulk Analysis & Sample Template")

    # Generate Sample CSV
    sample_df = pd.DataFrame({
        "Product": ["Item A", "Item B", "Item C"],
        "Price": [250, 999, 1500],
        "COGS": [100, 450, 700],
        "Platform": ["Amazon", "Flipkart", "Amazon"]
    })

    csv_buffer = io.StringIO()
    sample_df.to_csv(csv_buffer, index=False)
    st.download_button("📥 Download Sample CSV Template", data=csv_buffer.getvalue(), file_name="sample_2026_data.csv")

    st.divider()
    uploaded_file = st.file_uploader("Upload your completed CSV here", type="csv")
    if uploaded_file:
        df = pd.read_csv(uploaded_file)
        results = []
        for _, row in df.iterrows():
            calc = calculate_2026_economics(row['Platform'], row['Price'], row['COGS'])
            results.append({**row, "Profit": calc['profit'], "Margin": calc['margin'], "Recovery_Ratio": calc['recovery_ratio']})
        st.dataframe(pd.DataFrame(results), use_container_width=True)

with tab3:
    st.subheader("Price War Strategy")
    comp_p = st.number_input("Competitor Price to Match (₹)", value=price-50)
    surv = calculate_2026_economics(plat, comp_p, cogs, region)

    if surv['profit'] > 0:
        st.success(f"Safe to Match! New Profit: ₹{surv['profit']}")
    else:
        st.error(f"DANGER! Matching leads to ₹{abs(surv['profit'])} loss/unit.")

    st.subheader("📉 The Price Ladder (Sweet Spot Finder)")
    ladder = []
    for step in range(-150, 200, 50):
        tp = price + step
        ld = calculate_2026_economics(plat, tp, cogs, region)
        ladder.append({"Price": f"₹{tp}", "Profit": ld['profit'], "Margin": f"{ld['margin']}%", "Recovery_Ratio": ld['recovery_ratio']})
    st.table(pd.DataFrame(ladder))